# Generated by Django 4.2.7 on 2025-07-02 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(max_length=100)),
                ('structure_analyzed', models.BooleanField(default=False)),
                ('structure_data', models.JSONField(blank=True, null=True)),
                ('chunks_created', models.BooleanField(default=False)),
                ('total_chunks', models.IntegerField(default=0)),
                ('analysis_metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100)),
                ('element_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('level', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('structure_path', models.CharField(max_length=1000)),
                ('content_preview', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_elements', to='documents.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentstructure')),
            ],
            options={
                'ordering': ['page_number', 'line_number'],
                'unique_together': {('document', 'element_id')},
            },
        ),
        migrations.CreateModel(
            name='SemanticChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('structure_path', models.CharField(max_length=1000)),
                ('element_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('vector_embeddings', models.JSONField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_chunks', to='documents.document')),
                ('parent_chunks', models.ManyToManyField(blank=True, related_name='child_chunks_rel', to='documents.semanticchunk')),
                ('structure_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documentstructure')),
            ],
            options={
                'ordering': ['page_start'],
                'unique_together': {('document', 'chunk_id')},
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='documents.document')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('context_chunks', models.ManyToManyField(blank=True, related_name='context_sessions', to='documents.semanticchunk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
