# Generated by Django 4.2.7 on 2025-07-01 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='analysis_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='chunks_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='structure_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='structure_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SemanticChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('structure_path', models.CharField(max_length=1000)),
                ('chunk_type', models.CharField(max_length=50)),
                ('page_number', models.IntegerField()),
                ('chunk_order', models.IntegerField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_chunks', to='documents.document')),
            ],
            options={
                'ordering': ['page_number', 'chunk_order'],
                'unique_together': {('document', 'chunk_id')},
            },
        ),
        migrations.CreateModel(
            name='DocumentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100)),
                ('element_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('level', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('structure_path', models.CharField(max_length=1000)),
                ('content_preview', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_elements', to='documents.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentstructure')),
            ],
            options={
                'ordering': ['page_number', 'line_number'],
                'unique_together': {('document', 'element_id')},
            },
        ),
    ]
